version: '3.8'

services:
  backend:
    build:
      context: ./api
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d # Import SQL files during initialization
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081" # NGINX will run on 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Use custom NGINX configuration
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
