version: "3.8"
services:
  db:
    build: ./data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_data
    restart: always
  web:
    build: ./api
    environment:
      MYSQL_DATABASE: web_data
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
    ports:
      - "5000:443"
    depends_on:
      - db
    restart: on-failure